apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-service
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
    server: ''
  source:
    path: ./argocd
    repoURL: 'https://github.com/arunvel1988/appv1_argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false